[project]
name = "scallop-face-detection"
version = "0.0.2"
dependencies = [
  "face_detection",
  "torch",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."scallop.plugin"]
face-detection = "scallop_face_detection:ScallopFaceDetectionPlugin"
