[project]
name = "scallop-plip"
version = "0.0.2"
dependencies = [
  "transformers",
  "torch",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.entry-points."scallop.plugin"]
plip = "scallop_plip:ScallopPLIPPlugin"
