name: Scallop Core

on:
  push:
    branches: [ master ]
    paths:
      - "**.rs"
  pull_request:
    branches: [ master ]
    paths:
      - "**.rs"

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - nightly
    steps:
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: cargo test --verbose --workspace --release
